modLoader="javafml"
loaderVersion="[38,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
	modId="tbouncepad"
	version="2.1"
	displayName="Tinkers' Bounce Pad"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/tinkers-bounce-pad"
	logoFile="pack.png"
	credits="Me the mod author, thanks to kazmurenko for the Russian Translation"
	authors="MincraftEinstein"
	description='''
Adds the Bounce Pad from TConstruct 1.7.10 into newer versions.
'''

[modproperties.tbouncepad]
    catalogueImageIcon="pack.png"

[[dependencies.tbouncepad]]
    modId="forge"
    mandatory=true
    versionRange="[38,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tbouncepad]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18, 1.19)"
    ordering="NONE"
    side="BOTH"