modLoader="javafml" #mandatory

loaderVersion="[34,)" #mandatory

license="All rights reserved"

issueTrackerURL="http://my.issue.tracker/" #optional

[[mods]] #mandatory

modId="tbouncepad" #mandatory

version="1.3" #mandatory

displayName="Tinkers' Bounce Pad" #mandatory

updateJSONURL="http://myurl.me/" #optional

displayURL="https://www.curseforge.com/minecraft/mc-mods/tinkers-bounce-pad" #optional

logoFile="pack.png" #optional

credits="Me the mod author, thanks to kazmurenko for the Russian Translation" #optional

authors="MincraftEinstein" #optional

description='''
Adds The Bounce Pad Form TConstruct 1.7.10 into newer versions.
'''

[[dependencies.tbouncepad]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[34,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.tbouncepad]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.4]"
    ordering="NONE"
    side="BOTH"

[[dependencies.tbouncepad]]
    modId="einsteins_library"
    mandatory=true
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
