modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
#issueTrackerURL="https://change.me.to.your.issue.tracker.example.invalid/"

[[mods]]
	modId="tbouncepad"
	version="2.0"
	displayName="Tinkers' Bounce Pad"
	#updateJSONURL="https://change.me.example.invalid/updates.json"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/tinkers-bounce-pad"
	logoFile="pack.png"
	credits="Me the mod author, thanks to kazmurenko for the Russian Translation"
	authors="MincraftEinstein"
	itemIcon="tbouncepad:bounce_pad" #Used by Catalogue
	description='''
Adds the Bounce Pad from TConstruct 1.7.10 into newer versions.
'''

[[dependencies.tbouncepad]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tbouncepad]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3, 1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.tbouncepad]]
    modId="einsteins_library"
    mandatory=true
    versionRange="[2.0,)"
    ordering="AFTER"
    side="BOTH"
