modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "All rights reserved"
issueTrackerURL = "https://github.com/MincraftEinstein/TinkersBouncePad/issues"

[[mods]]
    modId = "tbouncepad"
    version = "${version}"
    displayName = "${mod_name}"
    #updateJSONURL = "https://change.me.example.invalid/updates.json"
    displayURL = "https://www.curseforge.com/minecraft/mc-mods/tinkers-bounce-pad"
    logoFile = "pack.png"
    authors = "${mod_author}"
    description = "${description}"

[[dependencies.tbouncepad]]
    modId = "neoforge"
    type = "required"
    versionRange = "[${neoforge_version},)"
    ordering = "NONE"
    side = "SERVER"

[[dependencies.tbouncepad]]
    modId = "minecraft"
    type = "required"
    versionRange = "${minecraft_version_range}"
    ordering = "NONE"
    side = "SERVER"
